from selenium import webdriver
from selenium.webdriver.common.by import By
from selenium.webdriver.support.ui import WebDriverWait
from selenium.webdriver.support import expected_conditions as ec
import pandas as pd
from pathlib import Path
import hsr_food
import hsr_calculator
    
props=[
    'calories',
    'fatContent',
    'saturatedFatContent',
    'cholesterolContent',
    'sodiumContent',
    'carbohydrateContent',
    'fiberContent',
    'sugarContent',
    'proteinContent',
    'vitaminDContent',
    'calciumContent',
    'ironContent',
    'potassiumContent',
]

dict_keys=[
    'Calories (kcal)',
    'Total fat (g)',
    'Saturated fat (g)',
    'Cholesterol (mg)',
    'Sodium (mg)',
    'Total carbohydrate (g)',
    'Dietary fiber (g)',
    'Sugars (g)',
    'Protein (g)',
    'Vitamin D (mcg)',
    'Calcium (mg)',
    'Iron (mg)',
    'Potassium (mg)',
]

food_category_dict={
            '1':['Orange juice',
                'Tomato juice',
                'Grape juice',
                'Banana juice',
                'Pineapple juice',
                'Apple juice',
                'Mango juice',
                'Water',
                'Coffee',
                'Decaf coffee',
                'Tea',
                'Green tea',
                'Peach tea',
                'Sweet tea',
                'Lemon tea',
                'Black tea',
                'Ginger tea',
                'Raspberry tea',
                'Pomegranate tea',
                'Soda',
                'Pepsi soda',
                'Sprite soda',
                'Orange soda',
                'Soda coca cola',
                'Diet soda',
                'Lemonade',
                'Limeade',
                'Jelly',
                'Soy milk',
                'Almond milk',
                'Hazelnut milk',
                'Coconut milk',
                'Espresso',
                'Soy latte',
                'Chai latte',
                'Almond milk latte',
                'Hazelnut latte',
            ],
           '1D':['Milk',
                 'Milkshake',
                 'Oreo milkshake',
                 'Vanilla milkshake',
                 'Chocolate milkshake',
                 'Strawberry milkshake',
                 'Chocolate milk',
                 'Vietnamese coffee',
                 'Latte',
                 'Mocha latte',
                 'Nonfat latte',
                 'Milk tea',
                 'Boba tea',
                 'Condensed milk',
                 'Hot chocolate',
                 'Smoothie',
                 'Banana smoothie',
                 'Strawberry smoothie',
                 'Spinach smoothie',
                 'Kiwi smoothie',
                 'Tropical smoothie',
                 'Pineapple smoothie',
                 'Cappuccino',
           ],
           '2':['Goi du du',
                'Salad',
                'Lecttuce salad',
                'Spinach salad',
                'Beet salad',
                'Greek salad',
                'Caesar salad',
                'Caprese salad',
                'Edamame salad',
                'Seaweed salad',
                'Pho',
                'Pho ga',
                'Pho nam', 
                'Banh mi',
                'Pork banh mi',
                'Chicken banh mi',
                'Banh goi',
                'Banh can',
                'Banh giay',
                'Banh cuon', 
                'Banh khot', 
                'Banh bot loc tran', 
                'Banh xeo', 
                'Banh tieu',
                'Banh trang',
                'Banh trung thu',
                'Canh chua', 
                'Bun bo hue',
                'Bun bo xao',
                'Bun thit nuong', 
                'Cha gio', 
                'Goi cuon',
                'Thit kho nuoc dua',
                'Bao',
                'Fried rice',
                'Kimchi fried rice',
                'Garlic fried rice',
                'Roasted duck',
                'Sushi',
                'Tuna sushi',
                'Salmon sushi',
                'Shrimp sushi',
                'Sushi california',
                'French fries',
                'Sweet potato fries',
                'Chicken burger',
                'Turkey burger',
                'Bacon burguer',
                'Hamburger',
                'Spaghetti',
                'Spaghetti carbonara',
                'Spaghetti bolognese',
                'Sausage spaghetti',
                'Chicken curry',
                'Fried chicken',
                'Fried chicken wing',
                'Fried chicken breast',
                'Fried chicken tenders',
                'Fried chicken drumstick',
                'Nugget',
                'Fish nugget',
                'Bbq chicken wings',
                'Bbq boneless wings',
                'Bbq buffalo wings',
                'Bbq honey wings',
                'Burrito',
                'Burrito beef',
                'Steak burrito',
                'Chicken burrito',
                'Donut',
                'Mapple donut',
                'Sandwich',
                'Ham sandwich',
                'Tuna sandwich',
                'Club sandwich',
                'Bacon sandwich',
                'Turkey sandwich',
                'Salmon sandwich',
                'Chicken sandwich',
                'Lobster roll sandwich',
                'Peanut butter sandwich',
                'Sashimi',
                'Takoyaki',
                'Tacos',
                'Fish tacos',
                'Beef tacos',
                'Chicken tacos',
                'Breakfast tacos',
                'Boiled egg',
                'Soft boiled egg',
                'Fried egg',
                'Deviled egg',
                'Omelette',
                'Stew',
                'Pork stew',
                'Lamb stew',
                'Seafood stew',
                'Chicken stew',
                'Beef stew',
                'Grilled fish',
                'Grilled steak',
                'Grilled salmon',
                'Grilled shrimp',
                'Grilled octopus',
                'Watermelon',
                'Banana',
                'Avocado',
                'Apple',
                'Orange',
                'Mandarins orange',
                'Mango',
                'Jackfruit',
                'Cabbage',
                'Red cabbage',
                'Spinach',
                'Strawberry',
                'Tomato',
                'Cucumber',
                'Carrot',
                'Cauliflower',
                'Broccoli',
                'Grape',
                'Pear',
                'Peach',
                'Pickle',
                'Popcorn',
                'Ramen',
                'Chicken ramen',
                'Tonkatsu ramen',
                'Miso ramen',
                'Miso soup',
                'Imitation crab',
                'Ham',
                'Pad thai',
                'Pork chop',
                'Prime rib',
                'Tofu',
                'Fried tofu',
                'Mapo tofu',
                'Pad thai',
                'Cooked rice',
                'Cooked brown rice',
                'Shrimp and grits',
                'Gyoza',
                'Grilled pork chop',
                'Fried pork chop',
                'Bbq pork chop',
                'Prime rib',
                'Beef carpaccio',
                'Salmon carpaccio',
                'Beef tartare',
                'Salmon tartare',
                'Beignet',
                'Bibimbap',
                'Beef bibimbap',
                'Tofu bibimbap',
                'Chicken bibimbap',
                'Ceviche',
                'Mixto ceviche',
                'Ceviche octopus',
                'Shrimp ceviche',
                'Scallop ceviche',
                'Chicken quesadilla',
                'Churros',
                'Clam chowder',
                'Corn chowder',
                'Crab chowder',
                'Seafood chowder',
                'Salmon chowder',
                'Crab cake',
                'Croque madame',
                'Dumpling',
                'Soup dumplings',
                'Fried dumpling',
                'Chicken dumplings',
                'Vegetable dumplings',
                'Shrimp dumpling',
                'Edamame',
                'Egg benedict',
                'Escargot',
                'Falafel',
                'Filet mignon',
                'Fish and chips',
                'Potato chips',
                'Sweet potato chips',
                'Foie gras',
                'Soup',
                'Bean soup',
                'Onion soup',
                'Potato soup',
                'Tomato soup',
                'Chicken soup',
                'Broccoli soup',
                'Garlic bread',
                'Garlic breadstick',
                'Gnocchi',
                'Hot dog',
                'Macaron',
                'Mussels',
                'Paella',
                'Veggie paella',
                'Seafood paella',
                'Samosa',
                'Chicken samosa',
                'Vegetable samosa',
                'Huevos ranchero',
                'Sticky rice',
                'Mango sticky rice',
                'Xoi',
                'Char siu',
                'Mochi',
                'Mango mochi',
                'Strawberry mochi',
                'Daifuku mochi',
            ],
           '2D':['Yogurt',
                 'Greek yogurt',
                 'Nonfat yogurt',
                 'Ice cream',
                 'Ice cream sandwich',
                 'Ice cream chocolate',
                 'Vanilla ice cream',
                 'Pudding',
                 'Bread pudding',
                 'Banana bread pudding',
                 'Pumpkin bread pudding',
                 'Nutella bread pudding',
                 'Bread pudding chocolate',
                 'Banana pudding',
                 'Crepe',
                 'Chocolate crepe',
                 'Fruit crepe',
                 'Cheesecake',
                 'Cheesecake pudding',
                 'Chocolate cheesecake',
                 'Strawberry cheesecake',
                 'Blueberry cheescake',
                 'Cake',
                 'Coffee cake',
                 'Chocolate cake',
                 'Red velvet cake',
                 'Carrot cake',
                 'Cookie',
                 'Oreo cookie',
                 'Chocolate chip cookie',
                 'Chocolate cookies',
                 'Biscuit',
                 'Egg biscuit',
                 'Chocolate biscuit',
                 'Butter biscuit',
                 'Waffle',
                 'Pancake',
                 'Pizza',
                 'Pepperoni pizza',
                 'Cheese pizza',
                 'Chocolate donut',
                 'Sour cream donut',
                 'Frosted donut',
                 'Grilled cheese',
                 'Butter popcorn',
                 'Custard pie',
                 'Custard',
                 'Flan',
                 'Chocolate',
                 'Brownie',
                 'Cupcake',
                 'Mini cupcake',
                 'Matcha cupcake',
                 'Pretzel',
                 'Croissant',
                 'Egg croissant',
                 'Chocolate croissant',
                 'French toast',
                 'Apple pie',
                 'Pumpkin pie',
                 'Sweet potato pie',
                 'Baklava',
                 'Cannoli',
                 'Mousse',
                 'Mango mousse',
                 'Lemon mousse',
                 'Pumpkin mousse',
                 'Strawberry mousse',
                 'Peanut butter mousse',
                 'Passion fruit mousse',
                 'Chocolate mousse',
                 'Creme brulee',
                 'Lasagna',
                 'Beef lasagna',
                 'Veggie lasagna',
                 'Cheese lasagna',
                 'Turkey lasagna',
                 'Macaroni and cheese',
                 'Lobster bisque',
                 'Tomato bisque',
                 'Crab bisque',
                 'Nachos',
                 'Nachos cheese',
                 'Fajita nachos',
                 'Pork nachos',
                 'Steak nachos',
                 'Nachos chicken',
                 'Veggie nachos',
                 'Chili nachos',
                 'Onion ring',
                 'Tiramisu',
                 'Shortcake',
                 'Strawberry shortcake',
                 'Cherry shortcake',
                 'Caramel shortcake',
                 'Risotto',
                 'Shrimp risotto',
                 'Chicken risotto',
                 'Pumpkin risotto',
                 'Short rib risotto',
                 'Mushroom risotto',
                 'Mashed potato',
                 'Mashed sweet potato',
                 'Mashed cauliflower',
                 'Poutine',
                 'Dark chocolate',
                 'Chocolate banana',
                 'Chocolate orange',
                 'Muffin',
                 'Egg muffin',
                 'Corn muffin',
                 'Bran muffin',
                 'Berry muffin',
                 'Banana muffin',
                 'Rasperry muffin',
                 'Chocolate chip muffin',
           ],
           '3':['Oils',
                'Palm oils',
                'Sesame oils',
                'Vegetable oils',
                'Coconut oils',
                'Margarine',
                'Butter',
           ],
           '3D':['Cheese',
                 'Blue cheese',
                 'Cheese plate',
                 'Feta cheese',
                 'Goat cheese',
                 'Swiss cheese',
                 'Cheddar cheese',
                 'Parmesan cheese',
                 'Mozzarella cheese',
                 'Cottage cheese',
                 'Khoa',
           ],
}

save_path = 'D:/Projects/HealthStarRating/Food-data/Nutrition-data/food-data.csv'
health_rated_save_path = 'D:/Projects/HealthStarRating/Food-data/Nutrition-data/heath-rated-food-data.csv'

def get_food_data(food_category_dict, save_path):
    food_dict={
    'Name':[],
    'Calories (kcal)':[],
    'Total fat (g)':[],
    'Saturated fat (g)':[],
    'Cholesterol (mg)':[],
    'Sodium (mg)':[],
    'Total carbohydrate (g)':[],
    'Dietary fiber (g)':[],
    'Sugars (g)':[],
    'Protein (g)':[],
    'Vitamin D (mcg)':[],
    'Calcium (mg)':[],
    'Iron (mg)':[],
    'Potassium (mg)':[],
    'Category':[],
    'Concentrated fruit and vegetable (%)':[],
    'FNVL (%)':[],
    }
    options=webdriver.FirefoxOptions()
    #options.add_argument('--headless')
    driver = webdriver.Firefox(options=options)
    for category in food_category_dict.keys():
        for food in food_category_dict[category]:
            try:
                food_dict['Name'].append(food)
                food_dict['Category'].append(str(category))
                food_dict['Concentrated fruit and vegetable (%)'].append(0.0)
                food_dict['FNVL (%)'].append(0.0)
                search_query = food.replace(" ", "-")
                url=f'https://www.nutritionix.com/food/{search_query}/100-g'
                driver.get(url)
            except:
                for key in dict_keys:
                    food_dict[key].append(0.0)
                print(f'Cannot find {food} data')              
            try:
                nutrition_label = WebDriverWait(driver,30).until(ec.presence_of_element_located((By.XPATH,"//div[@id='nutrition-label']//div[contains(@class,'nf-line')]")))
                for prop,key in zip(props,dict_keys):
                    try:
                        value = nutrition_label.find_element(By.XPATH,f"//span[contains(@itemprop,'{prop}')]")
                        value = driver.execute_script("return arguments[0].firstChild.textContent", value)
                        food_dict[key].append(float(value))
                    except:
                        food_dict[key].append(0.0)
            except:
                for key in dict_keys:
                    food_dict[key].append(0.0)
                print(f'Cannot find {food} data!')
    df=pd.DataFrame.from_dict(food_dict)
    csv_path = Path(save_path)
    df.to_csv(csv_path, index = False, mode = 'a', header = not csv_path.exists())
    driver.quit()

def get_health_star_rating(save_path, heath_rated_save_path):
    csv_path = Path(save_path)
    df = pd.read_csv(csv_path)
    health_stars = []
    for i in df.index:
        energy=(df['Calories (kcal)'][i])*4.184
        item=hsr_food.HSR_food(name = df['Name'][i], 
                       category = df['Category'][i], 
                       energy = energy, 
                       saturated_fat = df['Saturated fat (g)'][i], 
                       total_sugars = df['Sugars (g)'][i], 
                       sodium = df['Sodium (mg)'][i],
                       concentrated_fnvl= df['Concentrated fruit and vegetable (%)'][i],
                       fnvl=df['FNVL (%)'][i],
                       fibre=df['Dietary fiber (g)'][i],
                       protein=df['Protein (g)'][i]
        )
        health_star=hsr_calculator.get_health_star_rating(item)
        health_stars.append(health_star)
    df['Health Star Rating'] = health_stars
    modified_csv_path = Path(heath_rated_save_path)
    df.to_csv(modified_csv_path, index = False, mode = 'w')


# get_food_data(food_category_dict, save_path)
get_health_star_rating(save_path, health_rated_save_path)
